version: '3'

networks:
    application:
    # Prepared for proxy
    web:
        external: true

volumes:
    application:

services:
    nginx:
        restart: unless-stopped
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        env_file:
            - .env
        networks:
            # Prepared for proxy
            - web
            - application
        volumes:
            - application:/app
    # Comment ports section if you would like to use proxy
    #        ports:
    #          - 80:80

    uwsgi:
        restart: unless-stopped
        build:
            context: .
            dockerfile: docker/uwsgi/Dockerfile
        networks:
            - application
        volumes:
            - application:/app
        environment:
            - REDIS_HOST=redis

    redis:
        restart: unless-stopped
        image: redis:alpine
        volumes:
            - ./storage/redis:/data
        networks:
            - application
        command: redis-server --appendonly yes
